SELECT info.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO as info
 JOIN 
    (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) as SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID) as review
ON info.REST_ID = review.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE desc, FAVORITES desc;