SELECT USER_ID, NICKNAME, PRICE
FROM USED_GOODS_USER as b
JOIN (SELECT WRITER_ID, SUM(PRICE) AS PRICE
                        FROM USED_GOODS_BOARD
                        WHERE STATUS = 'DONE'
                        GROUP BY WRITER_ID) as a
ON b.USER_ID = a.WRITER_ID
WHERE PRICE >= 700000
ORDER BY PRICE;