SELECT MONTH(START_DATE) AS MONTH,CAR_ID, COUNT(CAR_ID) AS RECORDS
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE CAR_ID in (SELECT CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                  WHERE START_DATE LIKE '2022-08%' 
                        or START_DATE LIKE '2022-09%'
                        or START_DATE LIKE '2022-10%'
                  GROUP BY CAR_ID
                  HAVING COUNT(*)>=5)
        AND MONTH(START_DATE) IN ('8','9','10')
GROUP BY MONTH, CAR_ID
HAVING COUNT(CAR_ID)>0
ORDER BY MONTH, CAR_ID DESC;